# Configuration file of AnimVanish #
# -------------------------------- #

suppressToDate: true
notifyOps: false

# ---- EFFECTS ---- #

effects:
  herobrine:
    # Will the time set to night with the effect? Default: True
    night: true

  particle:
    # What particle will be used when using particle as the effect. Default: DRAGON_BREATH
    # You can find types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html#enum-constant-summary
    type: DRAGON_BREATH
    # How many particles will be spawned. Default: 50
    amount: 50


  sound:
    # What sound the player will hear. Default: BLOCK_AMETHYST_BLOCK_HIT
    # You can find types here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html#enum-constant-summary
    type: BLOCK_AMETHYST_BLOCK_HIT

  launch:
    # Enable if launch effect Armor Stands should use the player's own armor
    use_player_armor: true
