name: AnimVanish
version: '${project.version}'
main: eu.mikart.animvanish.Main
api-version: 1.18
author: ArikSquad
description: Beautiful library of pre-made effects to make vanishing look as cool as it can!
website: https://www.spigotmc.org/resources/animvanish-1-19-animated-vanishing.102183/
softdepend:
  - SuperVanish
  - PremiumVanish
  - Citizens
  - GSit

commands:
  animvanish:
    description: Command for information about the AnimVanish
    usage: /<command> [reload|help]
  invis:
    description: Command for invisibility with an effect
    usage: /<command> [effect]

permissions:
  animvanish.*:
    children:
      animvanish.invis: true
      animvanish.reload: true
      animvanish.help: true
    description: Grants you all the permissions in AnimVanish
  animvanish.invis:
    children:
      animvanish.invis.other: true
      animvanish.invis.lightning: true
      animvanish.invis.particle: true
      animvanish.invis.tnt: true
      animvanish.invis.npc: true
      animvanish.invis.blindness: true
      animvanish.invis.sound: true
      animvanish.invis.turn: true
      animvanish.invis.firework: true
      animvanish.invis.blood: true
      animvanish.invis.gui: true
      animvanish.invis.launch: true
    description: Grants all the invisibility effects
  animvanish.invis.gui:
    description: Grants you the ability to open the invis gui menu
  animvanish.invis.launch:
    description: Grants you the ability to launch yourself to the sky
  animvanish.invis.lightning:
    description: Grants you the ability to vanish with an amazing lightning strike
  animvanish.invis.particle:
    description: Grants you the ability to vanish with customizable particles
  animvanish.invis.tnt:
    description: Grants you the ability to vanish with an explosion
  animvanish.invis.npc:
    description: Grants you the ability to vanish with an NPC taking your place
  animvanish.invis.blindness:
    description: Grants you the ability to vanish with making players around you blind for a moment
  animvanish.invis.sound:
    description: Grants you the ability to vanish with a sound effect
  animvanish.invis.turn:
    description: Grants you the ability to vanish and making people around you turn away
  animvanish.invis.firework:
    description: Grants you the ability to vanish with colorful fireworks
  animvanish.invis.blood:
    description: Grants you the ability to vanish with blood
  animvanish.reload:
    description: Allows you to reload the plugin
  animvanish.help:
    default: true
    description: Allows you to use the help command

