name: AnimVanish
version: '${project.version}'
main: eu.mikart.animvanish.Main
api-version: 1.18
author: ArikSquad
description: Plugin that provides large library of pre-made effects to your vanish
website: https://youtube.com/c/ArikChannel
softdepend:
  - SuperVanish
  - PremiumVanish
  - Citizens

commands:
  animvanish:
    description: Main command for control
    usage: /<command> [reload|author|help]
  invis:
    description: Vanish using an effect
    usage: /<command> [herobrine|particle|tnt|npc|zombie]

permissions:
  animvanish.*:
    children:
      animvanish.invis: true
      animvanish.reload: true
      animvanish.help: true
    description: Grants you all the permissions in AnimVanish
  animvanish.invis:
    children:
      animvanish.invis.herobrine: true
      animvanish.invis.particle: true
      animvanish.invis.tnt: true
      animvanish.invis.npc: true
      animvanish.invis.zombie: true
      animvanish.invis.blindness: true
      animvanish.invis.sound: true
      animvanish.invis.turn: true
    description: Allows you to vanish with an effect
  animvanish.invis.herobrine:
    description: Allows you to vanish with herobrine effect
  animvanish.invis.particle:
    description: Allows you to vanish with a particle effect
  animvanish.invis.tnt:
    description: Allows you to vanish with a tnt effect
  animvanish.invis.npc:
    description: Allows you to vanish with an npc effect
  animvanish.invis.zombie:
    description:  Allows you to vanish with a zombie effect
  animvanish.invis.blindness:
    description: Allows you to vanish with a blindness effect
  animvanish.invis.sound:
    description: Allows you to vanish with a sound effect
  animvanish.invis.turn:
    description: Allows you to vanish with a spin effect
  animvanish.reload:
    description: Allows you to reload the plugin
  animvanish.help:
    default: true
    description: Allows you to use the help command

