name: Build AnimVanish

on: [ push, pull_request ]


jobs:
  plugin:
    name: Build the file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup java 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: build
        run: mvn clean package

      - name: Extract Maven project version
        run: echo "name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        id: project

      - name: List files
        run: ls -la

      - name: Upload Plugin jar
        uses: actions/upload-artifact@v4.6.0
        with:
          name: "AnimVanish"
          path: target/*.jar
