name: Build AnimVanish

on: [ push, pull_request ]

jobs:
  plugin:
    name: Build the file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: List files
        run: ls -la build/libs

      - name: Upload Plugin jar
        uses: actions/upload-artifact@v7
        with:
          name: "AnimVanish"
          path: build/libs/*.jar